### ISSUE TITLE
Minecraft screen stuck on Encrypting...

### ISSUE THREAD

**Issue by seahorse1seahorse** [LiveOverflow/minecraft-hacked#11]
So I set up a Paper server that works. I can connect to it and it works perfectly. (I disabled online mode because I have TLauncher).
I set the port for the Paper server 12345 (like in the video).
My server.properties file looks like this:

> #Minecraft server properties
#Mon May 02 17:53:56 BRT 2022
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
enable-command-block=false
gamemode=survival
enable-query=false
generator-settings={}
level-name=world
motd=A Minecraft Server
query.port=25565
pvp=true
generate-structures=true
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
max-players=20
use-native-transport=true
online-mode=false
enable-status=true
allow-flight=false
broadcast-rcon-to-ops=true
view-distance=10
resource-pack-prompt=
server-ip=
allow-nether=true
server-port=12345
enable-rcon=false
sync-chunk-writes=true
cracked=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=10
rcon.password=
player-idle-timeout=0
force-gamemode=false
debug=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
function-permission-level=2
level-type=default
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=16
max-world-size=29999984

So I tried to set up the teleport_proxy.py file like this:
`python3 teleport_proxy.py -q 12345`
The I try to connect to the local ip 127.0.0.1 (with Minecraft) There is no output. The screen in Minecraft is stuck on Encrypting... (after a while I get 'Timed Out')

When I try the same command with sudo I get:

> Traceback (most recent call last):
  File "/home/username/MCproxy/minecraft-hacked/01_protocol_proxy/teleport_proxy.py", line 2, in <module>
    from quarry.net.proxy import DownstreamFactory, Bridge
  File "/usr/local/lib/python3.10/dist-packages/quarry/net/proxy.py", line 3, in <module>
    from quarry.net.protocol import PacketDispatcher
  File "/usr/local/lib/python3.10/dist-packages/quarry/net/protocol.py", line 5, in <module>
    from quarry.types.buffer import BufferUnderrun, buff_types
  File "/usr/local/lib/python3.10/dist-packages/quarry/types/buffer/__init__.py", line 6, in <module>
    from quarry.types.buffer.v1_9 import Buffer1_9
  File "/usr/local/lib/python3.10/dist-packages/quarry/types/buffer/v1_9.py", line 2, in <module>
    from quarry.types.chunk import PackedArray, BlockArray
  File "/usr/local/lib/python3.10/dist-packages/quarry/types/chunk.py", line 2, in <module>
    from bitstring import BitArray, Bits
ModuleNotFoundError: No module named 'bitstring'

When I try to install bitstring with `pip3 install bitstring` I get:

> Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: bitstring in /home/username/.local/lib/python3.10/site-packages (3.1.9)

The same happens with proxy_hide_chat.py or any other .py file from quarry/examples/ (I get the No module named 'bitstring' error)

If someone finds the solution, please give me detailed steps, I am new to Java. Thank you!

**Comment by ToBlocky** [comment]
Have you tride setting server.properties to `rcon.port=25575
level-seed=
enable-command-block=false
gamemode=survival
enable-query=false
generator-settings={}
level-name=world
motd=A Minecraft Server
query.port=25565
pvp=true
generate-structures=true
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
max-players=20
use-native-transport=true
online-mode=false
enable-status=true
allow-flight=false
broadcast-rcon-to-ops=true
view-distance=10
resource-pack-prompt=
server-ip=
allow-nether=true
server-port=12345
enable-rcon=false
sync-chunk-writes=true
cracked=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=10
rcon.password=
player-idle-timeout=0
force-gamemode=false
debug=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
function-permission-level=2
level-type=default
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=16
max-world-size=29999984`
